### ISSUE TITLE
MySQL Exception Error

### ISSUE THREAD

**Issue by ghost** [Xazin/mybb_api#14]
Getting this error from UserCP when I try to generate an API key, freshly installed plugin.

```Fatal error: Uncaught mysqli_sql_exception: Data too long for column 'api_key' at row 1 in /var/www/<website>/inc/db_mysqli.php:332 Stack trace: #0 /var/www/<website>/inc/db_mysqli.php(332): mysqli_query() #1 /var/www/<website>/inc/db_mysqli.php(375): DB_MySQLi->query() #2 /var/www/<website>/inc/db_mysqli.php(953): DB_MySQLi->write_query() #3 /var/www/<website>/inc/plugins/api.php(354): DB_MySQLi->update_query() #4 /var/www/<website>/inc/class_plugins.php(142): usercp_manage() #5 /var/www/<website>/usercp.php(70): pluginSystem->run_hooks() #6 {main} thrown in /var/www/<website>/inc/db_mysqli.php on line 332```

**Comment by Xazin** [comment]
I will take a look this coming week.

What is your MyBB version?
